spring:
  application:
    name: study-manager

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

mail:
  address: ${MAIL_ADDRESS}
  apikey: ${SENDGRID_API_KEY}

jwt:
  secret: ${JWT_SECRET}